before:
  hooks:
builds:
  - id: "lambda"
    dir: "."
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - linux
    goarch:
      - amd64
archives:
  - id: "cfn-lambda"
    builds:
      - "lambda"
    format: zip
    name_template: 'cfn-lambda_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - "cfn-lambda/bootstrap"
  - id: "eventbridge-lambda"
    builds:
      - "lambda"
    format: zip
    name_template: 'eventbridge-lambda_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - "eventbridge-lambda/bootstrap"
release:
  draft: true
changelog:
  skip: true