version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: "cfn-lambda"
    dir: "cfn-lambda/"
    main: "."
    binary: "bootstrap"
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - linux
    goarch:
      - amd64
  - id: "eventbridge-lambda"
    dir: "eventbridge-lambda/"
    main: "."
    binary: "bootstrap"
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - linux
    goarch:
      - amd64
archives:
  - id: "cfn-lambda"
    builds:
      - "cfn-lambda"
    format: zip
    name_template: 'cfn-lambda_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  - id: "eventbridge-lambda"
    builds:
      - "eventbridge-lambda"
    format: zip
    name_template: 'eventbridge-lambda_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
release:
  draft: true
changelog:
  disable: true